### ISSUE TITLE
Deep paths don't work as expected

### ISSUE THREAD

**Issue by BnMcGn** [Shinmera/ubiquitous#1] opened 2016-04-05 15:49 UTC
```
CL-USER> (setf (ubiquitous:value 'something 'that 'goes 6 'levels 'deep) "Calling from the depths!")

"Calling from the depths!"
CL-USER> (ubiquitous:value 'something 'that 'goes 6 'levels 'deep)
NIL
NIL

CL-USER> (alexandria:hash-table-keys ubiquitous:*storage*)
(DEEP LEVELS 6 GOES THAT SOMETHING)

CL-USER> (ubiquitous:value 'deep)
"Calling from the depths!"
T

CL-USER> (ubiquitous:value 'something)
#<HASH-TABLE :TEST EQL :COUNT 0 {AC5F4B9}>
T
```

Running on sbcl 1.1.14

**Comment by Shinmera** [comment] 2016-04-05 18:20
Cannot reproduce on fba7dbd4bfb6b8ef3437fe1549f918bac8978070, SBCL 1.3.3.67-6763e98
```
CL-USER> (ql:quickload :ubiquitous)
To load "ubiquitous":
  Load 1 ASDF system:
    ubiquitous
; Loading "ubiquitous"

(:UBIQUITOUS)
CL-USER> (setf (ubiquitous:value 'something 'that 'goes 6 'levels 'deep) "Calling from the depths!")
"Calling from the depths!"
CL-USER> (ubiquitous:value 'something 'that 'goes 6 'levels 'deep)
"Calling from the depths!"
T
CL-USER> (ql:quickload :alexandria)
To load "alexandria":
  Load 1 ASDF system:
    alexandria
; Loading "alexandria"

(:ALEXANDRIA)
CL-USER> (alexandria:hash-table-keys ubiquitous:*storage*)
(SOMETHING)
```

**Comment by BnMcGn** [comment] 2016-04-05 20:00
Ok, I restarted my inferior lisp. Now it's working fine.

Will let you know if I can get it to happen again.

**Comment by Shinmera** [comment] 2016-04-05 20:02
Well, it happens. In the meantime I'll close this-- feel free to open it again if you can find a way to reproduce it.

**Closed by Shinmera** 2016-04-05 20:02 UTC
